#!/bin/bash

set -ouex pipefail

# Build Initramfs
KERNEL_VERSION="$(basename "$(find /usr/lib/modules -maxdepth 1 -type d | grep -v -E "*.img" | tail -n 1)")"
dracut --force --no-hostonly --reproducible --zstd --verbose \
  --kver "$KERNEL_VERSION" "/usr/lib/modules/$KERNEL_VERSION/initramfs.img"

if [ -f "/boot/vmlinuz-$KERNEL_VERSION" ]; then
  cp -f "/boot/vmlinuz-$KERNEL_VERSION" "/usr/lib/modules/$KERNEL_VERSION/vmlinuz"
fi