#!/bin/bash

set -ouex pipefail

echo "::group::Executing finalize"
trap 'echo "::endgroup::"' EXIT

# Clean folders for bootc
rm -rf \
    /boot \
    /home \
    /root \
    /srv

mkdir /boot
mkdir /root 
mkdir /home
mkdir /srv

# Set up ostree sysroot
if [ ! -d /sysroot ]; then
  mkdir /sysroot
  ln -s sysroot/ostree ostree
fi

# Ensure image first-boot works
rm -f /etc/machine-id